- name: check os
  shell: cat /etc/os-realease | grep CentOS
  register: os
  ignore_errors: true

- name: get docker
  get_url:
    url: https://get.docker.com
    dest: /home/{{ ansible_user }}/get-docker.sh

- name: install docker EE
  shell: sh get-docker.sh
  args:
    chdir: /home/{{ ansible_user }}/

- name: add user in docker group
  user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    groups: docker
    append: yes

- name: remove docker sh
  file:
    path: /home/{{ ansible_user }}/get-docker.sh
    state: absent

- name: start docker service
  systemd:
    name: docker
    state: started

- name: install python-pip (ubuntu)
  apt:
    name: 
      - python-pip
      - python
      - git
    state: latest
  when: os.rc != 0

- name: install EPEL repository
  yum:
    pkg: epel-release
    state: latest
  when: os.rc == 0

- name: install python-pip (CentOS)
  yum:
    name:
      - python
      - python-pip
      - git
    state: latest
  when: os.rc == 0

- name: upgrade pip
  shell: pip install --upgrade pip

- name: pip install docker
  pip:
    name: 
    - docker
    - jsondiff
    - pyyaml
    - docker-compose
    - zipp
    - ConfigParser
    - openshift